export const OrderIngredients = [{"_id":"60d3b41abdacab0026a733c6",
"name":"Краторная булка N-200i",
"type":"bun",
"proteins":80,
"fat":24,
"carbohydrates":53,
"calories":420,
"price":1255,
"image":"https://code.s3.yandex.net/react/code/bun-02.png",
"image_mobile":"https://code.s3.yandex.net/react/code/bun-02-mobile.png",
"image_large":"https://code.s3.yandex.net/react/code/bun-02-large.png",
"__v":0},
{"_id":"60d3b41abdacab0026a733d2",
"name":"Кристаллы марсианских альфа-сахаридов",
"type":"main",
"proteins":234,
"fat":432,
"carbohydrates":111,
"calories":189,
"price":762,
"image":"https://code.s3.yandex.net/react/code/core.png",
"image_mobile":"https://code.s3.yandex.net/react/code/core-mobile.png",
"image_large":"https://code.s3.yandex.net/react/code/core-large.png",
"__v":0},
{"_id":"60d3b41abdacab0026a733d3",
"name":"Мини-салат Экзо-Плантаго",
"type":"main",
"proteins":1,
"fat":2,
"carbohydrates":3,
"calories":6,
"price":4400,
"image":"https://code.s3.yandex.net/react/code/salad.png",
"image_mobile":"https://code.s3.yandex.net/react/code/salad-mobile.png",
"image_large":"https://code.s3.yandex.net/react/code/salad-large.png",
"__v":0},
{"_id":"60d3b41abdacab0026a733d4",
"name":"Сыр с астероидной плесенью",
"type":"main",
"proteins":84,
"fat":48,
"carbohydrates":420,
"calories":3377,
"price":4142,
"image":"https://code.s3.yandex.net/react/code/cheese.png",
"image_mobile":"https://code.s3.yandex.net/react/code/cheese-mobile.png",
"image_large":"https://code.s3.yandex.net/react/code/cheese-large.png",
"__v":0}]
 